services:
  mysql:
    image: mysql:8
    container_name: RentEase-Db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./Server
    container_name: RentEase-Server
    restart: unless-stopped
    volumes:
      - ./Server:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: renteasedb
      DB_USERNAME: root
      DB_PASSWORD: 123123321321@instance
    command: php artisan serve --host=0.0.0.0 --port=8000

  frontend:
    build:
      context: ./Client
    container_name: RentEase-Client
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
